[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "apex-utils"
version = "0.0.6"
authors = [
  { name="Tristan Engst", email="tristanengst@gmail.com" },
]
description = "Useful utility functions for deep learning research"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[options]
install_requires = [
    "torch>=1.10",
    "torchvision",
    "matplotlib",
    "gdown",
    "lmdb",
]

[project.urls]
"Homepage" = "https://github.com/tristanengst/apex-utils"

[pypi]
username = "__token__"
password = "pypi-AgEIcHlwaS5vcmcCJDM0MjA5MDU5LTA1MDItNDcyNy05MzJkLWM5ZGU4OWI3Y2VkYwACKlszLCI2ZmM2MTFlNS1kMjNkLTQ0ZTAtYmJjOS1hZTJmZGYxODE2NDEiXQAABiB90EakQxBbmYF5RbCDxmEk1fq7Yqy47MuMSKMkFcufUg"
